apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-buildpack-demo-1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-1/rhtap-buildpack-demo-1@sha256:c097aeb9835c85cbc7c5781c26d6d128c2749aeb3d454ce18017c9e3d758c94a
        name: my-java-quarkus
        resources: {}
status: {}
