apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-buildpack-demo-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-buildpack-demo-1
    app.kubernetes.io/part-of: rhtap-buildpack-demo-1
  name: rhtap-buildpack-demo-1alph
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: rhtap-buildpack-demo-1
    weight: null
status: {}
