apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-buildpack-demo-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-buildpack-demo-1
    app.kubernetes.io/part-of: rhtap-buildpack-demo-1
  name: rhtap-buildpack-demo-1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rhtap-buildpack-demo-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rhtap-buildpack-demo-1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-1/rhtap-buildpack-demo-1@sha256:c097aeb9835c85cbc7c5781c26d6d128c2749aeb3d454ce18017c9e3d758c94a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
